require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails'
require 'capistrano/monit'
require 'capistrano/env'
require 'capistrano/rails/console'

Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }
