forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/apt',        '1.4.0'
mod 'jfryman/nginx',         '0.0.5'
mod 'puppetlabs/nodejs',     '0.4.0'
mod 'puppetlabs/postgresql', '3.2.0'
mod 'saz/sudo',              '2.2.0'

mod 'rvm',
  git: 'git://github.com/naps62/puppet-rvm'

mod 'git',
  git: 'git://github.com/nesi/puppet-git',
  ref: '0.1.2'

mod 'gb',
  git: 'git://github.com/naps62/gb-puppet'
